### ISSUE TITLE
Alot of confusions :)

### ISSUE THREAD

**Issue by matesio** [trussworks/terraform-aws-rds-snapshot-cleaner#4]
I am planning to use this module in our AWS account to clean RDS snapshot but these variables confused me. If **cleaner_max_db_snapshot_count** is taking precedence then why we need to define **cleaner_retention_days**. one should be optional, I mean if it is taking precedence other would be ignored, isn't it? 

Moreover, the tags variable can also be optional. I know it is a good practice to tag resources for better management of AWS resources but there can be a case that one hasn't defined tags for snapshots. 

Where one can find the lambda function? the bucket defined in documentation is restricted. I tried running this module but it is giving **access denied** for the file one on S3 bucket. Please fix this else this is a completely useless module :)

![image](https://user-images.githubusercontent.com/23452747/87235486-cbb10000-c3f5-11ea-911d-fadf7488561f.png)

**Comment by eeeady** [comment]
Hi @matesio! 

Sorry for the delay in reply, I had to figure out what was going on with this repo. If you want to look at the Lambda code itself is in our truss-aws-tools repo here: https://github.com/trussworks/truss-aws-tools/blob/master/cmd/rds-snapshot-cleaner/main.go.

You have to build and push the code to your own s3 bucket and fill it in. I believe what we have in the documentation is just an example. We don't currently have a public s3 bucket to refer to since most of our clients don't want to pull code from an arbitrary s3 bucket. FWIW we know this is a bit of a pain point and have been discussing internally how to make these kinds of repos work better going forward.

It sounds like we should make `cleaner_max_db_snapshot_count` optional and leave `cleaner_retention_days` as required. I'll put that in the backlog to fix.

**Comment by avanti-joshi** [comment]
If you have any followups please feel free to re-open the issue, but closing for now since it's been inactive for over a year!
